### ISSUE TITLE
Unable to find revision in branch tn-imx_5.10.72_2.2.0-stable

### ISSUE THREAD

**Issue by aspauldingmchp** [TechNexion/linux-tn-imx#5]
When building **Yocto 3.3 Hardknott** from the Technexion BSP I get the following error:

Linux-tn-imx-5.10.72+gitAUTOINC+97258dd1dd-r0 do_fetch: Fetcher failure: Unable to find revision 97258dd1dd69d90d762b4c95cc4d5e4188413d2a in branch tn-imx_5.10.72_2.2.0-stable even from upstream.

I was previously able to source this commit without issue, now I cannot find it in the repository. Was this change backed out? 

I attempted to change the Yocto recipe to point to the latest commit on the Stable branch, but bitbake failed with "ExpansionError during parsing meta-tn-imx-bsp/recipes-kernel/linx/linux-tn-imx_5.10.bb"

How can I resolve this issue?

**Comment by ray-chang** [comment]
@aspauldingmchp 

Thanks for your feedback.

I used a clean container environment to build linux-tn-imx by following the steps below, and there was no problem.

> Fetch Yocto source:
> $: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-stable -m imx-5.10.72-2.2.0-2022Q2.xml
> $: repo sync -j8
> 
> Configure build target and start the build
> $: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=edm-g-imx8mp source tn-setup-release.sh -b build-xwayland-edm-g-imx8mp
> $: bitbake linux-tn-imx
> 

Maybe you need to do repo sync and then rebuild it.

BR,
Ray

**Comment by aspauldingmchp** [comment]
Thank you for the quick response. I've been able to point the `<meta-tn-imx-bsp>` layer to the latest version of branch tn-imx_5.10.72_2.2.0-stable. I am curios what happened to the commit we were previously targeting though. It appears that the commit still exists within the repository, but is no longer on a branch.

Was commit 97258dd removed from the stable branch?
