### ISSUE TITLE
Release date of the next stable version

### ISSUE THREAD

**Issue by takumiando** [TechNexion/linux-tn-imx#6]
Hi, I'm a PICO-IMX8MM user.
I'd like to use V4L2 controls with AR0522 camera module in our(company) project, but these features isn't merged yet in any stable releases.
I checked it is functional by cherry-picking, but we cannot use it because of our releasing policy.

When do you plan to release the next stable version?
I'd like to know milestone of releasing if you have.

**Comment by ray-chang** [comment]
@takumiando :

Thanks for your feedback.

The next stable release is expected after mid-November.
If you are in a hurry to verify, you can use the `next` branch.
https://github.com/TechNexion/linux-tn-imx/tree/tn-imx_5.15.71_2.2.0-next

BR,

Ray

**Comment by satosisotas** [comment]
Hi,
Thanks for your great works.
Now it's mid-November, how's going the next release?

**Comment by ray-chang** [comment]
@satosisotas :

Thank you for your patience.

Rapid verification is going to be done internally. The Rapid Verification version will be released by next Monday at the latest. Complete and careful verification must wait for one month.

BR,
Ray
